# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yTN1HvT9S5elwF6Mh26y1TIi1ALxJECn

# **SUGARCANE ANALYSIS**
"""

import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt

df=pd.read_csv("sugarcane.csv")

df.head()

df.shape

"""**DATA CLEANING**"""

df["Production (Tons)"]=df["Production (Tons)"].str.replace("."," ")
df["Production per Person (Kg)"]=df["Production per Person (Kg)"].str.replace("."," ")
df["Acreage (Hectare)"]=df["Acreage (Hectare)"].str.replace("."," ")
df["Yield (Kg / Hectare)"]=df["Yield (Kg / Hectare)"].str.replace("."," ")

df.rename(columns={"Production (Tons)": "Production(Tons)"}, inplace=True)

df.rename(columns={"Production per Person (Kg)": "Production_per_Person(Kg)"}, inplace=True)

df.rename(columns={"Acreage (Hectare)": "Acreage(Hectare)"}, inplace=True)

df.rename(columns={"Yield (Kg / Hectare)": "Yield(Kg/Hectare)"}, inplace=True)

df.isnull().sum()

df[df['Acreage(Hectare)'].isnull()]

df.dropna().reset_index()

df.drop(["index","Unnamed: 0"], axis= 1, inplace= True, errors='ignore')

df.head()

df.dtypes

df["Yield(Kg/Hectare)"]=df["Yield(Kg/Hectare)"].str.replace(" ","")
df["Yield(Kg/Hectare)"]=df["Yield(Kg/Hectare)"].str.replace(",","")
df["Production(Tons)"]=df["Production(Tons)"].str.replace(",","")
df["Production_per_Person(Kg)"]=df["Production_per_Person(Kg)"].str.replace(","," ")
df["Acreage(Hectare)"]=df["Acreage(Hectare)"].str.replace(","," ")

df.head()

df["Production(Tons)"]=df["Production(Tons)"].str.replace(" ","")
df["Production_per_Person(Kg)"]=df["Production_per_Person(Kg)"].str.replace(" ","")
df["Acreage(Hectare)"]=df["Acreage(Hectare)"].str.replace(" ","")

df["Yield(Kg/Hectare)"]= df["Yield(Kg/Hectare)"].astype(float)
df["Production(Tons)"]= df["Production(Tons)"].astype(float)
df["Production_per_Person(Kg)"]= df["Production_per_Person(Kg)"].astype(float)
df["Acreage(Hectare)"]= df["Acreage(Hectare)"].astype(float)

df.head()

df.dtypes

df.nunique()

"""**UNIVARIATE** **ANALYSIS**"""

df.head()

df['Continent'].value_counts()

df['Continent'].value_counts().plot(kind="bar")

plt.figure(figsize=(10,10))
plt.subplot(2,2,1)
sns.distplot(df['Production(Tons)'])
plt.subplot(2,2,2)
sns.distplot(df['Production_per_Person(Kg)'])
plt.subplot(2,2,3)
sns.distplot(df["Acreage(Hectare)"])
plt.subplot(2,2,4)
sns.distplot(df['Yield(Kg/Hectare)'])
plt.show()

plt.figure(figsize=(10,10))
plt.subplot(2,2,1)
sns.boxplot(df['Production(Tons)'])
plt.subplot(2,2,2)
sns.boxplot(df['Production_per_Person(Kg)'])
plt.subplot(2,2,3)
sns.boxplot(df["Acreage(Hectare)"])
plt.subplot(2,2,4)
sns.boxplot(df['Yield(Kg/Hectare)'])
plt.show()

df.describe()

"""**BIVARIATE ANALYSIS**

*WHICH COUNTRY PRODUCES MAXIMUM SUGARCANE*
"""

df_new = df[["Country","Production(Tons)"]].set_index("Country")

df.head()

df_new

df_new["Production(Tons)_percent"]= df_new["Production(Tons)"]*100/df_new["Production(Tons)"].sum()

df_new

df_new['Production(Tons)_percent'].plot(kind="pie",autopct="%0.2f")
plt.show()

df_new['Production(Tons)'].head(10).plot(kind="bar")

"""*HIGHEST YIELD*"""

df_yield=df.sort_values(by="Yield(Kg/Hectare)",ascending=False).head(10)
ax= sns.barplot(data=df_yield.head(10),x="Country",y="Production(Tons)")
ax.set_xticklabels(ax.get_xticklabels(), rotation=90)
plt.show()

"""*HIGHEST LAND*"""

df_acr=df.sort_values(by="Acreage(Hectare)",ascending=False).head(10)
ax= sns.barplot(data=df_acr.head(10),x="Country",y="Production(Tons)")
ax.set_xticklabels(ax.get_xticklabels(), rotation=90)
plt.show()

df.corr(numeric_only=True)

"""*DO COUNTRIES WITH HIGHEST LAND PRODUCE SUGARCANE*"""

sns.scatterplot(data=df, x="Acreage(Hectare)", y="Production(Tons)")

"""*ANALYSIS FOR CONTINENET*"""

df_continent= df.groupby("Continent").sum()
df_continent

df["Continent"].value_counts()

df_continent["number_of_countries"]=df.groupby("Continent").count()["Country"]

continent_names= df_continent.index.to_list()
sns.lineplot(data= df_continent, x="number_of_countries",y="Production(Tons)")
plt.xticks(df_continent["number_of_countries"],continent_names, rotation=90)
plt.show()